# Dockerfile

# Step 1: Use the official Python image
FROM python:3.12-slim

# Step 2: Set environment variables for Django settings
ENV PYTHONUNBUFFERED 1

# Step 3: Install dependencies
WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Step 4: Copy the Django app code
COPY . /app/

# Step 5: Expose the port
EXPOSE 8000

# Step 6: Run the app
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
